In [ ]:

import numpy as np
from pathlib import Path
import json
import joblib

from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from scipy.stats import spearmanr

import xgboost as xgb  # add near your imports (top of notebook)



import optuna
print(optuna.__version__)

4.7.0

c:\Users\aadha\anaconda3\envs\f1ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [14]:
from pathlib import Path
import fastf1

PROJECT_ROOT = Path.cwd().parents[1]  # adjust if needed
CACHE_DIR = PROJECT_ROOT / "data_raw" / "f1_cache"

fastf1.Cache.enable_cache(str(CACHE_DIR.resolve()))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("CACHE_DIR:", CACHE_DIR.resolve())




ART_DIR = Path.cwd() / "artifacts"
ART_DIR.mkdir(exist_ok=True)

print("ART_DIR:", ART_DIR.resolve())

PROJECT_ROOT: c:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory
CACHE_DIR: C:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\data_raw\f1_cache
ART_DIR: C:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\notebooks\Phase 3\artifacts

In [21]:

import json
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import fastf1



# --- experiment split ---
TRAIN_YEARS = list(range(2018, 2024))  # 2018..2023
EVAL_YEAR = 2024
TEST_YEAR = 2025

YEARS = TRAIN_YEARS + [EVAL_YEAR, TEST_YEAR]
SESSION = "Q"

TARGET = "quali_position"
ID_COLS = ["year", "round", "event_name",  "driver"]

print("Cache:", CACHE_DIR.resolve())
print("Years:", YEARS)

for y in YEARS:
    sched = fastf1.get_event_schedule(y)
    print(y, "schedule rows:", len(sched), "| cols:", list(sched.columns))

Cache: C:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\data_raw\f1_cache
Years: [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
2018 schedule rows: 21 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2019 schedule rows: 21 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2020 schedule rows: 19 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2021 schedule rows: 23 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2022 schedule rows: 24 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2023 schedule rows: 23 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2024 schedule rows: 25 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']
2025 schedule rows: 25 | cols: ['RoundNumber', 'Country', 'Location', 'OfficialEventName', 'EventDate', 'EventName', 'EventFormat', 'Session1', 'Session1Date', 'Session1DateUtc', 'Session2', 'Session2Date', 'Session2DateUtc', 'Session3', 'Session3Date', 'Session3DateUtc', 'Session4', 'Session4Date', 'Session4DateUtc', 'Session5', 'Session5Date', 'Session5DateUtc', 'F1ApiSupport']

In [22]:
import pandas as pd
import numpy as np
import fastf1

FEAT_PATH = ART_DIR / "df_feat.parquet"

feat_rows = []
fail_feat = []

for year in YEARS:
    try:
        sched = fastf1.get_event_schedule(year)
    except Exception as e:
        fail_feat.append((year, "schedule", type(e).__name__, str(e)))
        continue

    for _, ev in sched.iterrows():
        rnd = ev.get("RoundNumber")
        if pd.isna(rnd) or int(rnd) <= 0:
            continue
        rnd = int(rnd)

        event_name = ev.get("EventName")
        country = ev.get("Country")
        location = ev.get("Location")

        try:
            ses = fastf1.get_session(year, rnd, SESSION)

            # ✅ THIS is the big fix: you need laps=True for feature building
            ses.load(laps=True, telemetry=False, weather=False, messages=False)

            laps = ses.laps
            if laps is None or laps.empty:
                fail_feat.append((year, rnd, "EmptyLaps", event_name))
                continue

            # Standardize driver id to DriverNumber (matches well with results)
            if "DriverNumber" not in laps.columns:
                fail_feat.append((year, rnd, "NoDriverNumberInLaps", event_name))
                continue

            # Keep only "real" laps
            laps = laps.dropna(subset=["LapTime"]).copy()

            # Build a small but solid feature set per driver
            g = laps.groupby("DriverNumber", dropna=False)

            df_g = pd.DataFrame({
                "driver": g.size().index.astype(str),

                "n_laps": g.size().values,

                "best_laptime_s": g["LapTime"].min().dt.total_seconds().values,
                "avg_laptime_s": g["LapTime"].mean().dt.total_seconds().values,

                "best_s1_s": g["Sector1Time"].min().dt.total_seconds().values if "Sector1Time" in laps else np.nan,
                "best_s2_s": g["Sector2Time"].min().dt.total_seconds().values if "Sector2Time" in laps else np.nan,
                "best_s3_s": g["Sector3Time"].min().dt.total_seconds().values if "Sector3Time" in laps else np.nan,
            })

            df_g["year"] = year
            df_g["round"] = rnd
            df_g["event_name"] = event_name
            df_g["country"] = country
            df_g["location"] = location

            feat_rows.append(df_g)

        except Exception as e:
            fail_feat.append((year, rnd, type(e).__name__, str(e)))

df_feat = pd.concat(feat_rows, ignore_index=True) if feat_rows else pd.DataFrame()

print("df_feat:", df_feat.shape, "| failures:", len(fail_feat))
print("save ->", FEAT_PATH)
df_feat.to_parquet(FEAT_PATH, index=False)

assert not df_feat.empty, "df_feat is EMPTY — feature builder failed"
df_feat.head()
print("df_feat shape:", df_feat.shape)

assert not df_feat.empty, "df_feat is EMPTY — feature builder failed"

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '7', '5', '33', '3', '20', '8', '27', '55', '77', '14', '2', '11', '18', '31', '28', '9', '16', '35', '10']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['5', '7', '77', '44', '3', '10', '20', '27', '31', '55', '28', '11', '14', '2', '33', '8', '9', '35', '16', '18']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '35'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core           INFO 	Finished loading data for 20 drivers: ['5', '7', '77', '44', '33', '3', '27', '11', '55', '8', '20', '31', '14', '2', '28', '35', '10', '18', '16', '9']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '77', '3', '33', '7', '31', '11', '27', '55', '18', '35', '14', '16', '20', '2', '10', '9', '28', '8']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 28
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 28)
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '7', '33', '3', '20', '14', '55', '8', '2', '10', '31', '16', '11', '27', '9', '35', '18', '28']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 33
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 33)
core           INFO 	Finished loading data for 20 drivers: ['3', '5', '44', '7', '77', '31', '14', '55', '11', '10', '27', '2', '35', '16', '8', '28', '9', '18', '20', '33']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 8
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 8)
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '33', '44', '7', '3', '27', '31', '55', '11', '20', '28', '16', '14', '2', '10', '18', '35', '9', '8']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '3', '7', '55', '16', '20', '8', '31', '27', '11', '10', '9', '14', '28', '2', '35', '18']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '7', '33', '8', '3', '20', '55', '27', '31', '10', '16', '14', '18', '2', '11', '35', '28', '9']
core           INFO 	Loading data for British Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 28
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 28)
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '7', '77', '33', '3', '20', '8', '16', '31', '27', '11', '14', '10', '9', '55', '2', '35', '18', '28']
core           INFO 	Loading data for German Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['5', '77', '7', '33', '20', '8', '27', '55', '16', '11', '14', '35', '9', '44', '3', '31', '10', '28', '18', '2']
core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '7', '5', '55', '10', '33', '28', '20', '8', '14', '3', '27', '9', '18', '2', '16', '31', '11', '35']
core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '7'
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '31', '11', '8', '7', '33', '3', '20', '77', '10', '28', '16', '9', '27', '55', '14', '35', '18', '2']
core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['7', '5', '44', '77', '33', '8', '55', '31', '10', '18', '20', '35', '14', '27', '3', '11', '16', '28', '9', '2']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '77', '7', '3', '11', '8', '31', '27', '14', '55', '16', '9', '10', '20', '28', '2', '35', '18']
core           INFO 	Loading data for Russian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '7', '20', '31', '16', '11', '8', '9', '33', '3', '10', '55', '27', '28', '14', '35', '2', '18']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '7'
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '7', '8', '28', '10', '31', '5', '11', '16', '20', '55', '18', '3', '27', '35', '14', '2', '9']
core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '7', '77', '3', '31', '27', '8', '16', '11', '55', '20', '10', '28', '33', '14', '35', '18', '9', '2']
core           INFO 	Loading data for Mexican Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['3', '33', '44', '5', '77', '7', '27', '55', '16', '9', '31', '14', '11', '28', '10', '8', '2', '20', '18', '35']
core           INFO 	Loading data for Brazilian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '5', '77', '7', '33', '3', '9', '16', '8', '10', '20', '11', '31', '27', '35', '55', '28', '14', '18', '2']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '7', '3', '33', '8', '16', '31', '27', '55', '9', '20', '11', '14', '28', '10', '2', '35', '18']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '33', '16', '8', '20', '4', '7', '11', '27', '3', '23', '99', '26', '18', '10', '55', '63', '88']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['16', '5', '44', '77', '33', '20', '55', '8', '7', '4', '3', '23', '10', '11', '26', '99', '27', '18', '63', '88']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 23
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '16', '33', '10', '3', '27', '20', '8', '26', '11', '7', '55', '4', '18', '63', '88', '23', '99']
core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '11', '26', '4', '99', '16', '55', '3', '23', '20', '18', '8', '27', '63', '88', '7', '10']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['77', '44', '5', '33', '16', '10', '8', '20', '26', '3', '4', '23', '55', '7', '11', '27', '18', '99', '63', '88']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '10', '20', '3', '26', '55', '23', '27', '4', '8', '7', '99', '16', '11', '18', '63', '88']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core           INFO 	Finished loading data for 20 drivers: ['5', '44', '16', '3', '10', '77', '27', '4', '55', '20', '33', '26', '99', '23', '8', '11', '7', '18', '63', '88']
core           INFO 	Loading data for French Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

df_feat: (3432, 12) | failures: 0
save -> c:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\notebooks\Phase 3\artifacts\df_feat.parquet
df_feat shape: (3432, 12)

In [23]:
from pathlib import Path
import pandas as pd

print("CWD:", Path.cwd().resolve())

p = Path("artifacts") / "df_feat.parquet"
print("Relative parquet path resolves to:", p.resolve())
print("Exists?", p.exists(), "Size:", p.stat().st_size if p.exists() else None)

df_feat = pd.read_parquet(p)
print("Loaded df_feat shape:", df_feat.shape)
print("Columns:", list(df_feat.columns))
df_feat.head()

CWD: C:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\notebooks\Phase 3
Relative parquet path resolves to: C:\Users\aadha\OneDrive - Singapore Management University\Y2\S2\New folder\DAP\DAP F1 work\Working directory\notebooks\Phase 3\artifacts\df_feat.parquet
Exists? True Size: 129760
Loaded df_feat shape: (3432, 12)
Columns: ['driver', 'n_laps', 'best_laptime_s', 'avg_laptime_s', 'best_s1_s', 'best_s2_s', 'best_s3_s', 'year', 'round', 'event_name', 'country', 'location']

,driver,n_laps,best_laptime_s,avg_laptime_s,best_s1_s,best_s2_s,best_s3_s,year,round,event_name,country,location
0,10,5,85.295,103.418000,28.146,23.144,33.959,2018,1,Australian Grand Prix,Australia,Melbourne
1,11,10,84.005,95.566200,27.618,22.786,33.518,2018,1,Australian Grand Prix,Australia,Melbourne
2,14,10,83.597,96.737200,27.489,22.647,33.206,2018,1,Australian Grand Prix,Australia,Melbourne
3,16,6,84.636,96.620500,28.153,22.901,33.582,2018,1,Australian Grand Prix,Australia,Melbourne
4,18,9,84.230,98.978333,27.793,22.771,33.657,2018,1,Australian Grand Prix,Australia,Melbourne

In [24]:
# Cell 2 — Label builder df_lab (CACHE_ONLY-safe)

label_rows = []
fail_lab = []

# OPTION 1 (recommended): provide your own rounds per year.
# If you already have SG_ROUNDS elsewhere, use that and delete this dict.
# Example below assumes you only care about Singapore rounds.
SG_ROUNDS = {
    # year: round_number
    2018: 15,
    2019: 15,
    2022: 17,
    2023: 15,
    2024: 18,
    2025: 18,
    # add others you actually have cached
}

for year in YEARS:
    # Build the list of rounds without calling get_event_schedule (no internet needed)
    rounds = []
    if year in SG_ROUNDS:
        rounds = [int(SG_ROUNDS[year])]
    else:
        fail_lab.append((year, "schedule", "NoRoundMapping", "No round mapping for this year"))
        continue

    for rnd in rounds:
        try:
            ses = fastf1.get_session(year, rnd, SESSION)
            ses.load(laps=False, telemetry=False, weather=False, messages=False)

            # Metadata (safe even if schedule isn't fetched)
            event_name = getattr(ses.event, "EventName", None)
            country    = getattr(ses.event, "Country", None)
            location   = getattr(ses.event, "Location", None)

            res = ses.results
            if res is None or res.empty:
                fail_lab.append((year, rnd, "EmptyResults", event_name))
                continue

            driver_col = "DriverNumber" if "DriverNumber" in res.columns else "Abbreviation"

            for _, r in res.iterrows():
                label_rows.append({
                    "year": year,
                    "round": rnd,
                    "event_name": event_name,
                    "country": country,
                    "location": location,
                    "driver": str(r.get(driver_col, None)),
                    TARGET: r.get("Position", None),
                })

        except Exception as e:
            fail_lab.append((year, rnd, type(e).__name__, str(e)))

df_lab = pd.DataFrame(label_rows)
print("df_lab:", df_lab.shape, "| failures:", len(fail_lab))
df_lab.head()

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '5', '77', '7', '3', '11', '8', '31', '27', '14', '55', '16', '9', '10', '20', '28', '2', '35', '18']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['16', '44', '5', '33', '77', '23', '55', '27', '4', '11', '99', '10', '7', '20', '26', '18', '8', '63', '88', '3']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['16', '11', '44', '55', '14', '4', '10', '1', '20', '22', '63', '18', '47', '5', '24', '77', '3', '31', '23', '6']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['55', '63', '16', '4', '44', '20', '14', '31', '27', '40', '1', '10', '11', '23', '22', '77', '81', '2', '24', '18']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '81', '27', '14', '22', '16', '55', '23', '43', '11', '20', '31', '3', '18', '10', '77', '24']
core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '4', '44', '16', '6', '87', '14', '27', '30', '22', '5', '18', '43', '31', '10', '23', '55']

df_lab: (120, 7) | failures: 2

,year,round,event_name,country,location,driver,quali_position
0,2018,15,Singapore Grand Prix,Singapore,Singapore,44,1.0
1,2018,15,Singapore Grand Prix,Singapore,Singapore,33,2.0
2,2018,15,Singapore Grand Prix,Singapore,Singapore,5,3.0
3,2018,15,Singapore Grand Prix,Singapore,Singapore,77,4.0
4,2018,15,Singapore Grand Prix,Singapore,Singapore,7,5.0

In [25]:
# ==========================
# Cell 2.5 — Load df_feat artifact
# ==========================
from pathlib import Path

FEAT_PATH = Path("artifacts") / "df_feat.parquet"

if not FEAT_PATH.exists():
    raise RuntimeError("df_feat artifact not found. Run feature builder first.")

df_feat = pd.read_parquet(FEAT_PATH)

print("[df_feat] loaded")
print("[df_feat] shape:", df_feat.shape)
print("[df_feat] columns:", list(df_feat.columns))

[df_feat] loaded
[df_feat] shape: (3432, 12)
[df_feat] columns: ['driver', 'n_laps', 'best_laptime_s', 'avg_laptime_s', 'best_s1_s', 'best_s2_s', 'best_s3_s', 'year', 'round', 'event_name', 'country', 'location']

In [26]:
# ==========================
# Cell 3 — Merge + clean
# ==========================
df = df_feat.merge(df_lab, on=["year", "round", "event_name", "driver"], how="inner")

df_model = df.dropna(subset=[TARGET]).copy()
df_model[TARGET] = pd.to_numeric(df_model[TARGET], errors="coerce").astype(int)

print("merged df:", df.shape)
print("df_model:", df_model.shape)
print("years:", sorted(df_model["year"].unique()))
df_model[ID_COLS + [TARGET]].head()

merged df: (120, 15)
df_model: (120, 15)
years: [np.int64(2018), np.int64(2019), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

   year  round            event_name driver  quali_position
0  2018     15  Singapore Grand Prix     10              15
1  2018     15  Singapore Grand Prix     11               7
2  2018     15  Singapore Grand Prix     14              11
3  2018     15  Singapore Grand Prix     16              13
4  2018     15  Singapore Grand Prix     18              20

In [27]:
#debugg
# Debug: check merge keys exist
print("df_feat cols:", list(df_feat.columns))
print("df_lab  cols:", list(df_lab.columns))

keys = ["year", "round", "event_name", "driver"]
print("\nMissing in df_feat:", [k for k in keys if k not in df_feat.columns])
print("Missing in df_lab :", [k for k in keys if k not in df_lab.columns])

print("\nHead df_feat keys:")
display(df_feat[[c for c in keys if c in df_feat.columns]].head())

print("\nHead df_lab keys:")
display(df_lab[[c for c in keys if c in df_lab.columns]].head())

df_feat cols: ['driver', 'n_laps', 'best_laptime_s', 'avg_laptime_s', 'best_s1_s', 'best_s2_s', 'best_s3_s', 'year', 'round', 'event_name', 'country', 'location']
df_lab  cols: ['year', 'round', 'event_name', 'country', 'location', 'driver', 'quali_position']

Missing in df_feat: []
Missing in df_lab : []

Head df_feat keys:

   year  round             event_name driver
0  2018      1  Australian Grand Prix     10
1  2018      1  Australian Grand Prix     11
2  2018      1  Australian Grand Prix     14
3  2018      1  Australian Grand Prix     16
4  2018      1  Australian Grand Prix     18

Head df_lab keys:

   year  round            event_name driver
0  2018     15  Singapore Grand Prix     44
1  2018     15  Singapore Grand Prix     33
2  2018     15  Singapore Grand Prix      5
3  2018     15  Singapore Grand Prix     77
4  2018     15  Singapore Grand Prix      7

In [28]:
# ==================================
# Cell 4 — Build X/y splits by years
# ==================================
# Numeric feature columns = everything except ids + target
drop_cols = set(ID_COLS + [TARGET])
num_cols = [c for c in df_model.columns if c not in drop_cols]

# Keep only numeric columns (defensive)
X_all = df_model[num_cols].apply(pd.to_numeric, errors="coerce")
y_all = df_model[TARGET].astype(float)

train_df = df_model[df_model["year"].isin(TRAIN_YEARS)].copy()
eval_df  = df_model[df_model["year"] == EVAL_YEAR].copy()
test_df  = df_model[df_model["year"] == TEST_YEAR].copy()

X_train = train_df[num_cols].apply(pd.to_numeric, errors="coerce")
y_train = train_df[TARGET].astype(float)

X_eval = eval_df[num_cols].apply(pd.to_numeric, errors="coerce")
y_eval = eval_df[TARGET].astype(float)

X_test = test_df[num_cols].apply(pd.to_numeric, errors="coerce")
y_test = test_df[TARGET].astype(float)

print("Splits:",
      "train", X_train.shape,
      "eval", X_eval.shape,
      "test", X_test.shape,
      "| n_features", len(num_cols))

Splits: train (80, 10) eval (20, 10) test (20, 10) | n_features 10

In [29]:
# ===========================
# Cell 5 — Metrics helpers
# ===========================
def calc_metrics(y_true, y_pred):
    mae = float(mean_absolute_error(y_true, y_pred))
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    sp = float(spearmanr(y_true, y_pred).correlation)
    return {"mae": mae, "rmse": rmse, "spearman": sp}

OPTIM_MODE = "rmse"  # minimize RMSE on eval
def score_for_optim(y_true, y_pred):
    m = calc_metrics(y_true, y_pred)
    return m["rmse"]

In [32]:
## ======================================
# Cell 6 — Optuna objective + run
# ======================================
SEED = 42
N_TRIALS = 40

dtrain = xgb.DMatrix(X_train, label=y_train)
deval  = xgb.DMatrix(X_eval,  label=y_eval)

def objective(trial: optuna.Trial):
    params = {
        # core booster params
        "eta": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 0.1, 20.0, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "gamma": trial.suggest_float("gamma", 0.0, 10.0),
        "lambda": trial.suggest_float("reg_lambda", 1e-4, 50.0, log=True),
        "alpha": trial.suggest_float("reg_alpha", 1e-6, 10.0, log=True),

        # fixed
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "seed": SEED,
        "tree_method": "hist",
    }

    num_boost_round = trial.suggest_int("n_estimators", 200, 1400, step=100)

    booster = xgb.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=num_boost_round,
        evals=[(deval, "eval")],
        early_stopping_rounds=50,
        verbose_eval=False
    )

    # predict using best iteration if available
    best_iter = getattr(booster, "best_iteration", None)
    if best_iter is not None:
        pred_eval = booster.predict(deval, iteration_range=(0, best_iter + 1))
    else:
        pred_eval = booster.predict(deval)

    score = score_for_optim(y_eval, pred_eval)

    m = calc_metrics(y_eval, pred_eval)
    trial.set_user_attr("eval_mae", m["mae"])
    trial.set_user_attr("eval_rmse", m["rmse"])
    trial.set_user_attr("eval_spearman", m["spearman"])
    trial.set_user_attr("best_iteration", best_iter)

    return score

study = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=SEED))
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("Best score:", study.best_value)
print("Best params:", study.best_params)

[I 2026-02-25 13:09:43,688] A new study created in memory with name: no-name-0d6e182c-6f55-4565-9d67-e564ace2ed11
Best trial: 1. Best value: 4.50026:  10%|█         | 4/40 [00:00<00:01, 21.80it/s]

[I 2026-02-25 13:09:43,750] Trial 0 finished with value: 4.8395974028439745 and parameters: {'learning_rate': 0.030710573677773714, 'max_depth': 10, 'min_child_weight': 4.83437145318464, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'gamma': 1.5599452033620265, 'reg_lambda': 0.0002142973316927139, 'reg_alpha': 1.156732719914599, 'n_estimators': 900}. Best is trial 0 with value: 4.8395974028439745.
[I 2026-02-25 13:09:43,782] Trial 1 finished with value: 4.500260360232703 and parameters: {'learning_rate': 0.08341106432362087, 'max_depth': 3, 'min_child_weight': 17.052641538983092, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381, 'gamma': 1.8182496720710062, 'reg_lambda': 0.0011097286548581117, 'reg_alpha': 0.000134801802908908, 'n_estimators': 800}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:43,824] Trial 2 finished with value: 4.820501269183085 and parameters: {'learning_rate': 0.03647316284911211, 'max_depth': 5, 'min_child_weight': 2.5579488960947363, 'subsample': 0.569746930326021, 'colsample_bytree': 0.6460723242676091, 'gamma': 3.663618432936917, 'reg_lambda': 0.03973096924910799, 'reg_alpha': 0.3134958021096912, 'n_estimators': 400}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:43,883] Trial 3 finished with value: 4.826938274604336 and parameters: {'learning_rate': 0.04666963767236924, 'max_depth': 7, 'min_child_weight': 0.12790390175145838, 'subsample': 0.8037724259507192, 'colsample_bytree': 0.5852620618436457, 'gamma': 0.6505159298527952, 'reg_lambda': 25.566437378681954, 'reg_alpha': 5.746775499181867, 'n_estimators': 1200}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:43,923] Trial 4 finished with value: 4.541074055339335 and parameters: {'learning_rate': 0.0249064396938244, 'max_depth': 3, 'min_child_weight': 3.753537145233125, 'subsample': 0.7200762468698007, 'colsample_bytree': 0.5610191174223894, 'gamma': 4.951769101112702, 'reg_lambda': 0.00015702874159436434, 'reg_alpha': 2.318690670290199, 'n_estimators': 500}. Best is trial 1 with value: 4.500260360232703.

Best trial: 1. Best value: 4.50026:  18%|█▊        | 7/40 [00:00<00:01, 22.41it/s]

[I 2026-02-25 13:09:43,955] Trial 5 finished with value: 4.724496864433846 and parameters: {'learning_rate': 0.07277150634170934, 'max_depth': 5, 'min_child_weight': 1.572867419497858, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'gamma': 9.695846277645586, 'reg_lambda': 2.6149218241872196, 'reg_alpha': 3.7713131110779936, 'n_estimators': 1300}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:43,997] Trial 6 finished with value: 4.851078539363148 and parameters: {'learning_rate': 0.059963338824126605, 'max_depth': 10, 'min_child_weight': 0.15981734133214875, 'subsample': 0.5979914312095727, 'colsample_bytree': 0.522613644455269, 'gamma': 3.2533033076326436, 'reg_lambda': 0.016408172581661183, 'reg_alpha': 7.933105363733024e-05, 'n_estimators': 1200}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:44,094] Trial 7 finished with value: 4.5567115025460865 and parameters: {'learning_rate': 0.02911701023242742, 'max_depth': 5, 'min_child_weight': 1.7732091590842103, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'gamma': 0.7455064367977082, 'reg_lambda': 42.09582733145515, 'reg_alpha': 0.2545150013091294, 'n_estimators': 400}. Best is trial 1 with value: 4.500260360232703.

Best trial: 11. Best value: 4.38952:  30%|███       | 12/40 [00:00<00:01, 19.27it/s]

[I 2026-02-25 13:09:44,203] Trial 8 finished with value: 4.861439067893741 and parameters: {'learning_rate': 0.010166803740022877, 'max_depth': 9, 'min_child_weight': 4.231554618260076, 'subsample': 0.8645035840204937, 'colsample_bytree': 0.8856351733429728, 'gamma': 0.7404465173409036, 'reg_lambda': 0.01103787406036786, 'reg_alpha': 6.472669269538641e-06, 'n_estimators': 1300}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:44,240] Trial 9 finished with value: 4.860084541021799 and parameters: {'learning_rate': 0.06470376604234768, 'max_depth': 5, 'min_child_weight': 0.14003921591980473, 'subsample': 0.6554911608578311, 'colsample_bytree': 0.6625916610133735, 'gamma': 7.29606178338064, 'reg_lambda': 0.4299529224880894, 'reg_alpha': 1.6236379661338332, 'n_estimators': 800}. Best is trial 1 with value: 4.500260360232703.
[I 2026-02-25 13:09:44,277] Trial 10 finished with value: 4.481680311952296 and parameters: {'learning_rate': 0.18168388620005324, 'max_depth': 3, 'min_child_weight': 17.018997474271167, 'subsample': 0.9762904054253753, 'colsample_bytree': 0.7728591400411078, 'gamma': 6.902470735691452, 'reg_lambda': 0.00285604212867136, 'reg_alpha': 0.0006732595215632083, 'n_estimators': 800}. Best is trial 10 with value: 4.481680311952296.
[I 2026-02-25 13:09:44,313] Trial 11 finished with value: 4.389518204663476 and parameters: {'learning_rate': 0.1984877499318177, 'max_depth': 3, 'min_child_weight': 15.008473953050952, 'subsample': 0.9856075751261574, 'colsample_bytree': 0.7692492775881494, 'gamma': 7.026992327579986, 'reg_lambda': 0.00137863977608311, 'reg_alpha': 0.001758502488555402, 'n_estimators': 800}. Best is trial 11 with value: 4.389518204663476.
[I 2026-02-25 13:09:44,356] Trial 12 finished with value: 4.39151524631351 and parameters: {'learning_rate': 0.18127429301993012, 'max_depth': 3, 'min_child_weight': 18.260714046799492, 'subsample': 0.9993825915423253, 'colsample_bytree': 0.7734942910835931, 'gamma': 7.177459817699898, 'reg_lambda': 0.0018256926995654885, 'reg_alpha': 0.008523873535958997, 'n_estimators': 600}. Best is trial 11 with value: 4.389518204663476.

Best trial: 13. Best value: 4.38067:  45%|████▌     | 18/40 [00:00<00:01, 21.69it/s]

[I 2026-02-25 13:09:44,397] Trial 13 finished with value: 4.380674721660194 and parameters: {'learning_rate': 0.19762750325534964, 'max_depth': 7, 'min_child_weight': 10.462720928231722, 'subsample': 0.9996812193207756, 'colsample_bytree': 0.7819301846117483, 'gamma': 7.693830937826342, 'reg_lambda': 0.0023802047494851466, 'reg_alpha': 0.012432541913714651, 'n_estimators': 200}. Best is trial 13 with value: 4.380674721660194.
[I 2026-02-25 13:09:44,437] Trial 14 finished with value: 4.4608627608491 and parameters: {'learning_rate': 0.11693705189321676, 'max_depth': 7, 'min_child_weight': 8.057205711864189, 'subsample': 0.9259670417321502, 'colsample_bytree': 0.9977875972075845, 'gamma': 9.003890440895372, 'reg_lambda': 0.15295946757406942, 'reg_alpha': 0.013994996910761288, 'n_estimators': 300}. Best is trial 13 with value: 4.380674721660194.
[I 2026-02-25 13:09:44,482] Trial 15 finished with value: 4.852452913718414 and parameters: {'learning_rate': 0.1270114313891049, 'max_depth': 8, 'min_child_weight': 0.4597142162227327, 'subsample': 0.8782966152939655, 'colsample_bytree': 0.7171909647569544, 'gamma': 8.148982240747142, 'reg_lambda': 0.00047202178448779513, 'reg_alpha': 0.04941013019311272, 'n_estimators': 200}. Best is trial 13 with value: 4.380674721660194.
[I 2026-02-25 13:09:44,525] Trial 16 finished with value: 4.53558434047049 and parameters: {'learning_rate': 0.11946602024366813, 'max_depth': 6, 'min_child_weight': 8.546829525130935, 'subsample': 0.9380113029185004, 'colsample_bytree': 0.8345924183767854, 'gamma': 5.769491738896778, 'reg_lambda': 0.005820703185606939, 'reg_alpha': 0.0018381148802684459, 'n_estimators': 1000}. Best is trial 13 with value: 4.380674721660194.
[I 2026-02-25 13:09:44,564] Trial 17 finished with value: 5.174551144512979 and parameters: {'learning_rate': 0.19101237951974145, 'max_depth': 8, 'min_child_weight': 0.5875100487180402, 'subsample': 0.8446610900995984, 'colsample_bytree': 0.7274678992262075, 'gamma': 5.7948115683448655, 'reg_lambda': 0.0008608898323938978, 'reg_alpha': 1.7952862002476622e-06, 'n_estimators': 600}. Best is trial 13 with value: 4.380674721660194.

Best trial: 18. Best value: 4.1093:  52%|█████▎    | 21/40 [00:01<00:01, 17.65it/s]

[I 2026-02-25 13:09:44,640] Trial 18 finished with value: 4.109304682789168 and parameters: {'learning_rate': 0.018457814696648665, 'max_depth': 6, 'min_child_weight': 9.48255844654336, 'subsample': 0.5016176221472306, 'colsample_bytree': 0.8313890569413005, 'gamma': 8.44192315586728, 'reg_lambda': 0.046574247820414964, 'reg_alpha': 0.0004978412468008696, 'n_estimators': 200}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:44,711] Trial 19 finished with value: 4.49741692562251 and parameters: {'learning_rate': 0.018638532294243032, 'max_depth': 6, 'min_child_weight': 0.7633697714682962, 'subsample': 0.5216004247704905, 'colsample_bytree': 0.8380228898406453, 'gamma': 9.965575899978141, 'reg_lambda': 0.7559802176289697, 'reg_alpha': 0.00014182203153390867, 'n_estimators': 200}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:44,799] Trial 20 finished with value: 4.297094526621769 and parameters: {'learning_rate': 0.01291483690989417, 'max_depth': 8, 'min_child_weight': 8.58552041333122, 'subsample': 0.6977951920543067, 'colsample_bytree': 0.964051434116436, 'gamma': 8.385870667059155, 'reg_lambda': 0.06417624333119706, 'reg_alpha': 1.4769469454280287e-05, 'n_estimators': 200}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  57%|█████▊    | 23/40 [00:01<00:01, 15.93it/s]

[I 2026-02-25 13:09:44,888] Trial 21 finished with value: 4.393077215495649 and parameters: {'learning_rate': 0.0127028507043692, 'max_depth': 8, 'min_child_weight': 7.551190556751483, 'subsample': 0.6999434748899485, 'colsample_bytree': 0.9867145705142458, 'gamma': 8.506171326413018, 'reg_lambda': 0.0709417190934203, 'reg_alpha': 5.4915796552848306e-06, 'n_estimators': 200}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:44,964] Trial 22 finished with value: 4.1317341097844755 and parameters: {'learning_rate': 0.017589890147134902, 'max_depth': 7, 'min_child_weight': 9.127015921950765, 'subsample': 0.6415540137945439, 'colsample_bytree': 0.94635836524905, 'gamma': 8.069052403443507, 'reg_lambda': 0.04492005315589974, 'reg_alpha': 0.00035281041572736226, 'n_estimators': 400}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,037] Trial 23 finished with value: 4.415516732606657 and parameters: {'learning_rate': 0.01614621764172957, 'max_depth': 6, 'min_child_weight': 5.749981293813844, 'subsample': 0.6402371943614807, 'colsample_bytree': 0.9400131173613441, 'gamma': 8.765491501992416, 'reg_lambda': 0.1597110345864669, 'reg_alpha': 3.053836125488312e-05, 'n_estimators': 400}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  68%|██████▊   | 27/40 [00:01<00:00, 14.51it/s]

[I 2026-02-25 13:09:45,102] Trial 24 finished with value: 4.440115228253479 and parameters: {'learning_rate': 0.01892464555385134, 'max_depth': 9, 'min_child_weight': 2.870368190788798, 'subsample': 0.5269274900831309, 'colsample_bytree': 0.9330781524491712, 'gamma': 6.336746601219149, 'reg_lambda': 0.03552772881087874, 'reg_alpha': 0.0005363885124748765, 'n_estimators': 600}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,194] Trial 25 finished with value: 4.33759299506877 and parameters: {'learning_rate': 0.013484797914128746, 'max_depth': 8, 'min_child_weight': 11.75189243397943, 'subsample': 0.6586127315496917, 'colsample_bytree': 0.8487462758467241, 'gamma': 9.052992144305385, 'reg_lambda': 2.322685814373576, 'reg_alpha': 2.966542507773461e-05, 'n_estimators': 300}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,265] Trial 26 finished with value: 4.535082064504348 and parameters: {'learning_rate': 0.02317794871240489, 'max_depth': 9, 'min_child_weight': 6.137080268017892, 'subsample': 0.716762001065279, 'colsample_bytree': 0.9539943821550264, 'gamma': 7.873984219578644, 'reg_lambda': 0.14681648229685706, 'reg_alpha': 0.0005708835061411531, 'n_estimators': 300}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  72%|███████▎  | 29/40 [00:01<00:00, 13.30it/s]

[I 2026-02-25 13:09:45,357] Trial 27 finished with value: 4.540505694339467 and parameters: {'learning_rate': 0.010472442684040358, 'max_depth': 4, 'min_child_weight': 0.9454429584691917, 'subsample': 0.6147898174200794, 'colsample_bytree': 0.8752155348994586, 'gamma': 4.684126896425554, 'reg_lambda': 0.6027961690931297, 'reg_alpha': 1.413046992943952e-05, 'n_estimators': 500}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,448] Trial 28 finished with value: 4.437461479142557 and parameters: {'learning_rate': 0.014757582693043489, 'max_depth': 7, 'min_child_weight': 2.35341261737815, 'subsample': 0.5058041774299645, 'colsample_bytree': 0.9158840279963768, 'gamma': 9.380196714472616, 'reg_lambda': 0.012316938528020436, 'reg_alpha': 2.0913101203189774e-06, 'n_estimators': 500}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,530] Trial 29 finished with value: 4.600285376893458 and parameters: {'learning_rate': 0.02085224855917066, 'max_depth': 10, 'min_child_weight': 0.2803157453314437, 'subsample': 0.681867593368197, 'colsample_bytree': 0.8124923307129746, 'gamma': 6.32861336057996, 'reg_lambda': 0.03877892427174395, 'reg_alpha': 6.457338983836864e-05, 'n_estimators': 300}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  78%|███████▊  | 31/40 [00:02<00:00, 13.50it/s]

[I 2026-02-25 13:09:45,591] Trial 30 finished with value: 4.714472824537234 and parameters: {'learning_rate': 0.03819959264610298, 'max_depth': 6, 'min_child_weight': 4.403044424607206, 'subsample': 0.7384586976152966, 'colsample_bytree': 0.9623493081481518, 'gamma': 8.347217093157337, 'reg_lambda': 1.4231723527687388, 'reg_alpha': 0.00040146935769882445, 'n_estimators': 400}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,705] Trial 31 finished with value: 4.452533232286224 and parameters: {'learning_rate': 0.013652784853121009, 'max_depth': 8, 'min_child_weight': 11.638870033176836, 'subsample': 0.6649068138403129, 'colsample_bytree': 0.8789816927241437, 'gamma': 9.135448029900006, 'reg_lambda': 9.048467453013425, 'reg_alpha': 2.387101878081469e-05, 'n_estimators': 300}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  82%|████████▎ | 33/40 [00:02<00:00, 12.12it/s]

[I 2026-02-25 13:09:45,797] Trial 32 finished with value: 4.344831490308304 and parameters: {'learning_rate': 0.011698333011078508, 'max_depth': 9, 'min_child_weight': 11.316638662730945, 'subsample': 0.6225496560990353, 'colsample_bytree': 0.8326210038223775, 'gamma': 9.983055277344166, 'reg_lambda': 6.11800043307, 'reg_alpha': 0.00015674325206496706, 'n_estimators': 200}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:45,885] Trial 33 finished with value: 4.3366552617786205 and parameters: {'learning_rate': 0.016880341679993575, 'max_depth': 8, 'min_child_weight': 13.221201481509903, 'subsample': 0.5580449474245316, 'colsample_bytree': 0.8681604906557757, 'gamma': 7.7948292573896705, 'reg_lambda': 0.341030351739613, 'reg_alpha': 8.232926330341662e-06, 'n_estimators': 300}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093:  92%|█████████▎| 37/40 [00:02<00:00, 12.10it/s]

[I 2026-02-25 13:09:45,987] Trial 34 finished with value: 4.1250406637697035 and parameters: {'learning_rate': 0.016465664250335434, 'max_depth': 7, 'min_child_weight': 6.3429975199440385, 'subsample': 0.5555522700282238, 'colsample_bytree': 0.9772967984617106, 'gamma': 7.87240435792225, 'reg_lambda': 0.28013214012403137, 'reg_alpha': 8.326847539329918e-06, 'n_estimators': 400}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:46,063] Trial 35 finished with value: 4.207317645381925 and parameters: {'learning_rate': 0.027697893337160752, 'max_depth': 7, 'min_child_weight': 5.773025591494742, 'subsample': 0.5430898923244905, 'colsample_bytree': 0.9610673316462865, 'gamma': 3.695914202425522, 'reg_lambda': 0.07521391525983098, 'reg_alpha': 1.3121975816503044e-06, 'n_estimators': 700}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:46,135] Trial 36 finished with value: 4.386090096929104 and parameters: {'learning_rate': 0.028923064461466686, 'max_depth': 7, 'min_child_weight': 3.1625373634070764, 'subsample': 0.5467898288411918, 'colsample_bytree': 0.9191447014513826, 'gamma': 2.9048626921074314, 'reg_lambda': 0.023927231240217815, 'reg_alpha': 1.129609552412407e-06, 'n_estimators': 700}. Best is trial 18 with value: 4.109304682789168.

Best trial: 18. Best value: 4.1093: 100%|██████████| 40/40 [00:02<00:00, 14.88it/s]

[I 2026-02-25 13:09:46,208] Trial 37 finished with value: 4.244173810777112 and parameters: {'learning_rate': 0.03629876442551651, 'max_depth': 6, 'min_child_weight': 6.05587015878336, 'subsample': 0.5949594398609022, 'colsample_bytree': 0.9841108908151044, 'gamma': 4.193526423780509, 'reg_lambda': 0.006142341584677172, 'reg_alpha': 0.005066379277934959, 'n_estimators': 900}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:46,294] Trial 38 finished with value: 4.256950495070916 and parameters: {'learning_rate': 0.023282915880184153, 'max_depth': 7, 'min_child_weight': 5.500588300924541, 'subsample': 0.5724416339318958, 'colsample_bytree': 0.9002912394269258, 'gamma': 3.1162233966391324, 'reg_lambda': 0.07568676725993549, 'reg_alpha': 3.5084129982544526e-06, 'n_estimators': 700}. Best is trial 18 with value: 4.109304682789168.
[I 2026-02-25 13:09:46,373] Trial 39 finished with value: 4.479220248350037 and parameters: {'learning_rate': 0.025723585484087482, 'max_depth': 6, 'min_child_weight': 1.9734990805744506, 'subsample': 0.5395612598390027, 'colsample_bytree': 0.9662956030297999, 'gamma': 4.126698243068059, 'reg_lambda': 0.21405207254136624, 'reg_alpha': 6.44897073978033e-05, 'n_estimators': 1000}. Best is trial 18 with value: 4.109304682789168.
Best score: 4.109304682789168
Best params: {'learning_rate': 0.018457814696648665, 'max_depth': 6, 'min_child_weight': 9.48255844654336, 'subsample': 0.5016176221472306, 'colsample_bytree': 0.8313890569413005, 'gamma': 8.44192315586728, 'reg_lambda': 0.046574247820414964, 'reg_alpha': 0.0004978412468008696, 'n_estimators': 200}

In [33]:
# ======================================
# Cell 7 — Train best model + evaluate
# ======================================
best = study.best_params

# convert optuna params -> xgb params (note: lambda/alpha keys)
best_xgb_params = {
    "eta": best["learning_rate"],
    "max_depth": best["max_depth"],
    "min_child_weight": best["min_child_weight"],
    "subsample": best["subsample"],
    "colsample_bytree": best["colsample_bytree"],
    "gamma": best["gamma"],
    "lambda": best["reg_lambda"],
    "alpha": best["reg_alpha"],

    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "seed": 42,
    "tree_method": "hist",
}

num_boost_round = best["n_estimators"]

dtrain = xgb.DMatrix(X_train, label=y_train)
deval  = xgb.DMatrix(X_eval,  label=y_eval)

best_booster = xgb.train(
    params=best_xgb_params,
    dtrain=dtrain,
    num_boost_round=num_boost_round,
    evals=[(deval, "eval")],
    early_stopping_rounds=50,
    verbose_eval=False
)

best_iter = getattr(best_booster, "best_iteration", None)
if best_iter is not None:
    pred_eval = best_booster.predict(deval, iteration_range=(0, best_iter + 1))
else:
    pred_eval = best_booster.predict(deval)

print("Best iteration:", best_iter)
print("Eval metrics:", calc_metrics(y_eval, pred_eval))

Best iteration: 122
Eval metrics: {'mae': 3.5067500829696656, 'rmse': 4.109304682789168, 'spearman': 0.7020318014449615}

In [34]:
# ======================================
# Cell 8 — Fit on train+eval, predict test
# ======================================
X_train_full = pd.concat([X_train, X_eval], axis=0)
y_train_full = pd.concat([y_train, y_eval], axis=0)

dtrain_full = xgb.DMatrix(X_train_full, label=y_train_full)
dtest       = xgb.DMatrix(X_test)

final_booster = xgb.train(
    params=best_xgb_params,
    dtrain=dtrain_full,
    num_boost_round=(best_iter + 1) if best_iter is not None else num_boost_round,
    verbose_eval=False
)

pred_test = final_booster.predict(dtest)
print("Test metrics:", calc_metrics(y_test, pred_test))

Test metrics: {'mae': 3.661785674095154, 'rmse': 4.960741329840325, 'spearman': 0.7694622582512833}

In [35]:
from pathlib import Path
ART_DIR = Path("artifacts")
ART_DIR.mkdir(exist_ok=True, parents=True)

final_booster.save_model(str(ART_DIR / "xgb_best.json"))
print("Saved:", ART_DIR / "xgb_best.json")

Saved: artifacts\xgb_best.json